/********************************************************
 * Program Filename: lemur.h
 * Author: Evan Garrison
 * Date: 05/14/2021
 * Description: Lemur class header file
 * Input: Lemur name, class, bank size
 * Output: Lemur status, price, revenue generated.
 ********************************************************/

//Begins header guard
#ifndef LEMUR_H
#define LEMUR_H

//includes base class
#include "animal.h"

/*
 * Lemur class declaration.
 * This class inherits members from its base class, Animal.
 * It has members used to manipulate the more specific components of the BlackBear class
 */
class Lemur : public Animal {
    //private members
    private:
        static const int price = 700; //price of 1 lemur
        static const int revenue = 140; //revenue generated by a lemur

    //public members
    public:
        Lemur(); //default constructor
        Lemur(std::string n, int a=0); //Constructor with user defined parameters

        /*
         * Public member functions(methods) for BlackBear class.
         * a detailed description of each function is given in the implementation file
         */
        int getRevenue() const; //gets revenue
        int getPrice() const; //gets price
        void advanceMonth(int &costs, int &rev, const int &bank); //advances month, adds costs and revenue
};

//End header guard
#endif