/********************************************************
 * Program Filename: tiger.cpp
 * Author: Evan Garrison
 * Date: 05/14/2021
 * Description: Tiger class implementation file
 * Input: Tiger name, class, bank size
 * Output: Tiger status, price, revenue generated.
 ********************************************************/

#include "tiger.h"

/********************************************************
 * Function: Tiger Constructor
 * Description: Constructor for Tiger class
 * Parameters: n - name of tiger, a - age of tiger
 * Pre-Conditions: Tiger has not been created
 * Post-Conditions: Tiger has been created with name n and age a
 ********************************************************/
Tiger::Tiger(std::string n, int a) : Animal(n, a) {
}

/********************************************************
 * Function: Tiger default Constructor
 * Description: Default Constructor for Tiger class
 * Parameters: none
 * Pre-Conditions: Tiger has not been created
 * Post-Conditions: Tiger is created with no name, age 0
 ********************************************************/
Tiger::Tiger() {
}

/********************************************************
 * Function: getRevenue
 * Description: gets revenue generated by tigers
 * Parameters: none
 * Pre-Conditions: caller doesn't have revenue generated
 * Post-Conditions: caller has been given revenue value
 ********************************************************/
int Tiger::getRevenue() const {
    return revenue; //returns revenue
}

/********************************************************
 * Function: getPrice
 * Description: gets price of Tiger
 * Parameters: none
 * Pre-Conditions: caller doesn't have price
 * Post-Conditions: caller has been give price
 ********************************************************/
int Tiger::getPrice() const {
    return price; //returns price
}

/********************************************************
 * Function: advanceMonth
 * Description: advances month for Tiger, calculates cost and revenue generated,
 * heals/kills is sick.
 * Parameters: &costs - reference to running cost, &rev - reference to
 * running revenue, &bank - const reference to money in bank
 * Pre-Conditions: Lemur still has values and conditions from  last month
 * Post-Conditions: Lemurs condition has been advanced, revenue and cost
 * has been added to running tally
 ********************************************************/
void Tiger::advanceMonth(int &costs, int &rev, const int &bank) {
    Animal::advanceMonth(costs); //calls base function for advanceMonth

    if (getSick()) //if the animals sick, heal/kill it
        heal(costs, bank, getPrice());

    /*
     * If the animal isn't dead, this calculated revenue generated and adds it to the
     * to the running revenue. revenue generated for babies is double the normal.
     */
    if (!getDead()) {
        if (getLifeStage() == BABY)
            rev += getRevenue() * 2;
        else
            rev += getRevenue();
    }
}